import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const exampleVaultPluginDir =
	"budget-form-example-vault/.obsidian/plugins/obsidian-budget-form";

const copyToExampleVault = {
	name: "copy-to-example-vault",
	setup(build) {
		build.onEnd(() => {
			copyFileSync("main.js", `${exampleVaultPluginDir}/main.js`);
			copyFileSync("manifest.json", `${exampleVaultPluginDir}/manifest.json`);
			copyFileSync("styles.css", `${exampleVaultPluginDir}/styles.css`);
			copyFileSync(
				"node_modules/hledger-wasm/dist/hledger-wasm.wasm",
				`${exampleVaultPluginDir}/hledger-wasm.wasm`
			);
			copyFileSync("hledger-worker.js", `${exampleVaultPluginDir}/hledger-worker.js`);
		});
	},
};

// Build the Web Worker first (bundles browser_wasi_shim into it)
await esbuild.build({
	entryPoints: ["hledger-worker.ts"],
	bundle: true,
	format: "iife",
	target: "es2020",
	treeShaking: true,
	outfile: "hledger-worker.js",
	logLevel: "info",
});

// Build the main plugin
esbuild
	.build({
		banner: {
			js: banner,
		},
		entryPoints: ["main.ts"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr",
			...builtins,
		],
		format: "cjs",
		watch: !prod,
		target: "es2020",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outfile: "main.js",
		plugins: [copyToExampleVault],
	})
	.catch(() => process.exit(1));